In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname = "C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family= font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

In [2]:
OTT = pd.read_excel("data/가장많이이용하는OTT서비스(20-21).xlsx", header=[0,1], index_col=[0,1])
OTT

C:\Users\gyeoa\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

구분별(2)        2020                                                         \
구분별(2)     사례수 (명) TV 방송 프로그램 (VOD/다시보기) (%) 해외 TV 방송 프로그램 (%) 실시간 TV (%)
전체 소계       7434.0                      57.0               5.3       24.5
성별 남        3872.0                      54.9               5.5       24.9
   여        3562.0                      59.2               4.9       24.0
연령 만10대미만    173.0                      24.9               0.0       12.3
   만10-19세   825.0                      48.6               2.6       18.3
   만20-29세  1378.0                      62.6               8.7       27.1
   만30-39세  1420.0                      57.8               7.5       32.1
   만40-49세  1481.0                      64.9               5.4       25.2
   만50-59세  1373.0                      55.3               3.3       21.4
   만60-69세   666.0                      49.9               2.1       19.2
   만70세이상    119.0                      46.9               3.0       19.5

구분별(2)                                                                        \
구분별(2)     영화 (%) OTT 사업자 자체 제작 프로그램(넷플릭스 오리지널 등) (%) 예능/오락(개인방송 콘텐츠 포함) (%)
전체 소계        22.3                                19.8                   73.1
성별 남         23.9                                20.4                   75.2
   여         20.6                                19.1                   70.8
연령 만10대미만     3.2                                 9.7                   85.7
   만10-19세   15.9                                12.9                   79.6
   만20-29세   34.8                                23.9                   73.7
   만30-39세   30.6                                28.2                   69.6
   만40-49세   23.6                                19.4                   69.2
   만50-59세   14.8                                16.8                   73.9
   만60-69세    7.9                                12.9                   74.4
   만70세이상     3.5                                10.3                   76.0

구분별(2)                      2021                                        \
구분별(2)     음악 (%) 기타 (%) 사례수 (명) 영화 (%) 예능/오락(개인방송 콘텐츠 포함) (%) 드라마 (%)
전체 소계        32.1    0.3  8293.7   38.5                   80.5    47.0
성별 남         30.3    0.4  4283.5   37.4                   78.6    33.2
   여         34.1    0.3  4010.2   39.8                   82.5    61.7
연령 만10대미만    19.8    1.0   174.5    8.1                   71.3     7.1
   만10-19세   40.4    0.9   880.1   30.7                   88.8    31.1
   만20-29세   34.1    0.3  1381.4   61.5                   88.7    57.0
   만30-39세   30.8    0.1  1390.1   46.9                   86.4    53.2
   만40-49세   32.0    0.4  1585.9   45.1                   79.8    52.7
   만50-59세   30.0    0.3  1580.6   29.8                   75.2    45.8
   만60-69세   31.5    0.2  1025.7   18.1                   69.6    42.7
   만70세이상    15.2    0.0   275.5   13.5                   64.2    31.5

구분별(2)
구분별(2)     교양/다큐멘터리 (%) 교육/학습 (%) 애니메이션(만화) (%) 스포츠 (%) 뉴스 (%) 기타 (%)
전체 소계              19.6       9.2          10.2    23.4   25.8    2.0
성별 남               20.6       8.4           9.3    39.9   29.7    1.7
   여               18.6      10.1          11.2     5.8   21.6    2.2
연령 만10대미만           9.3      41.8          72.9     0.3    0.9    0.0
   만10-19세         12.4      36.1          39.1     9.9    5.1    1.6
   만20-29세         19.9       8.9          10.5    22.7   11.3    0.9
   만30-39세         19.1       5.9           8.6    29.9   21.1    1.8
   만40-49세         18.6       4.7           4.6    26.8   29.5    1.7
   만50-59세         21.4       4.3           1.5    28.3   36.1    2.6
   만60-69세         25.4       1.9           1.0    20.7   45.5    2.9
   만70세이상          25.6       3.2           1.4    15.3   48.9    4.3

In [3]:
OTT.columns =[["2020","2020","2020","2020","2020","2020","2020","2020","2020","2021","2021","2021","2021","2021","2021","2021","2021","2021","2021"], ["사례수","국내TV", "해외TV", "실시간TV", "영화", "OTT자체제작", "개인방송(예능/오락)", "음악", "기타","사례수", "영화", "개인방송(예능/오락)", "드라마","교양/다큐","교육/학습","애니메이션","스포츠","뉴스","기타"]]

In [4]:
OTT

              2020                                                        \
               사례수  국내TV 해외TV 실시간TV    영화 OTT자체제작 개인방송(예능/오락)    음악   기타
전체 소계       7434.0  57.0  5.3  24.5  22.3    19.8        73.1  32.1  0.3
성별 남        3872.0  54.9  5.5  24.9  23.9    20.4        75.2  30.3  0.4
   여        3562.0  59.2  4.9  24.0  20.6    19.1        70.8  34.1  0.3
연령 만10대미만    173.0  24.9  0.0  12.3   3.2     9.7        85.7  19.8  1.0
   만10-19세   825.0  48.6  2.6  18.3  15.9    12.9        79.6  40.4  0.9
   만20-29세  1378.0  62.6  8.7  27.1  34.8    23.9        73.7  34.1  0.3
   만30-39세  1420.0  57.8  7.5  32.1  30.6    28.2        69.6  30.8  0.1
   만40-49세  1481.0  64.9  5.4  25.2  23.6    19.4        69.2  32.0  0.4
   만50-59세  1373.0  55.3  3.3  21.4  14.8    16.8        73.9  30.0  0.3
   만60-69세   666.0  49.9  2.1  19.2   7.9    12.9        74.4  31.5  0.2
   만70세이상    119.0  46.9  3.0  19.5   3.5    10.3        76.0  15.2  0.0

              2021
               사례수    영화 개인방송(예능/오락)   드라마 교양/다큐 교육/학습 애니메이션   스포츠    뉴스   기타
전체 소계       8293.7  38.5        80.5  47.0  19.6   9.2  10.2  23.4  25.8  2.0
성별 남        4283.5  37.4        78.6  33.2  20.6   8.4   9.3  39.9  29.7  1.7
   여        4010.2  39.8        82.5  61.7  18.6  10.1  11.2   5.8  21.6  2.2
연령 만10대미만    174.5   8.1        71.3   7.1   9.3  41.8  72.9   0.3   0.9  0.0
   만10-19세   880.1  30.7        88.8  31.1  12.4  36.1  39.1   9.9   5.1  1.6
   만20-29세  1381.4  61.5        88.7  57.0  19.9   8.9  10.5  22.7  11.3  0.9
   만30-39세  1390.1  46.9        86.4  53.2  19.1   5.9   8.6  29.9  21.1  1.8
   만40-49세  1585.9  45.1        79.8  52.7  18.6   4.7   4.6  26.8  29.5  1.7
   만50-59세  1580.6  29.8        75.2  45.8  21.4   4.3   1.5  28.3  36.1  2.6
   만60-69세  1025.7  18.1        69.6  42.7  25.4   1.9   1.0  20.7  45.5  2.9
   만70세이상    275.5  13.5        64.2  31.5  25.6   3.2   1.4  15.3  48.9  4.3

In [5]:
OTT["시청증가율"] = OTT["2021"]["사례수"]/OTT["2020"]["사례수"] *100

In [6]:
OTT
# 2020년에 비해 2021년의 OTT시청 사례수는 30-39세를 제외하고 모든 연령대가 증가하였다.

              2020                                                        \
               사례수  국내TV 해외TV 실시간TV    영화 OTT자체제작 개인방송(예능/오락)    음악   기타
전체 소계       7434.0  57.0  5.3  24.5  22.3    19.8        73.1  32.1  0.3
성별 남        3872.0  54.9  5.5  24.9  23.9    20.4        75.2  30.3  0.4
   여        3562.0  59.2  4.9  24.0  20.6    19.1        70.8  34.1  0.3
연령 만10대미만    173.0  24.9  0.0  12.3   3.2     9.7        85.7  19.8  1.0
   만10-19세   825.0  48.6  2.6  18.3  15.9    12.9        79.6  40.4  0.9
   만20-29세  1378.0  62.6  8.7  27.1  34.8    23.9        73.7  34.1  0.3
   만30-39세  1420.0  57.8  7.5  32.1  30.6    28.2        69.6  30.8  0.1
   만40-49세  1481.0  64.9  5.4  25.2  23.6    19.4        69.2  32.0  0.4
   만50-59세  1373.0  55.3  3.3  21.4  14.8    16.8        73.9  30.0  0.3
   만60-69세   666.0  49.9  2.1  19.2   7.9    12.9        74.4  31.5  0.2
   만70세이상    119.0  46.9  3.0  19.5   3.5    10.3        76.0  15.2  0.0

              2021                                                             \
               사례수    영화 개인방송(예능/오락)   드라마 교양/다큐 교육/학습 애니메이션   스포츠    뉴스   기타
전체 소계       8293.7  38.5        80.5  47.0  19.6   9.2  10.2  23.4  25.8  2.0
성별 남        4283.5  37.4        78.6  33.2  20.6   8.4   9.3  39.9  29.7  1.7
   여        4010.2  39.8        82.5  61.7  18.6  10.1  11.2   5.8  21.6  2.2
연령 만10대미만    174.5   8.1        71.3   7.1   9.3  41.8  72.9   0.3   0.9  0.0
   만10-19세   880.1  30.7        88.8  31.1  12.4  36.1  39.1   9.9   5.1  1.6
   만20-29세  1381.4  61.5        88.7  57.0  19.9   8.9  10.5  22.7  11.3  0.9
   만30-39세  1390.1  46.9        86.4  53.2  19.1   5.9   8.6  29.9  21.1  1.8
   만40-49세  1585.9  45.1        79.8  52.7  18.6   4.7   4.6  26.8  29.5  1.7
   만50-59세  1580.6  29.8        75.2  45.8  21.4   4.3   1.5  28.3  36.1  2.6
   만60-69세  1025.7  18.1        69.6  42.7  25.4   1.9   1.0  20.7  45.5  2.9
   만70세이상    275.5  13.5        64.2  31.5  25.6   3.2   1.4  15.3  48.9  4.3

                 시청증가율

전체 소계       111.564434
성별 남        110.627583
   여        112.582819
연령 만10대미만   100.867052
   만10-19세  106.678788
   만20-29세  100.246734
   만30-39세   97.894366
   만40-49세  107.083052
   만50-59세  115.120175
   만60-69세  154.009009
   만70세이상   231.512605

In [7]:
OTT_movie = pd.DataFrame([OTT["2020"]["영화"], OTT["2021"]["영화"]], index=["2020","2021"]).T

In [8]:
OTT_movie["OTT영화시청증가율"]=OTT_movie["2021"]/OTT_movie["2020"]*100

In [9]:
OTT_movie

            2020  2021  OTT영화시청증가율
전체 소계       22.3  38.5  172.645740
성별 남        23.9  37.4  156.485356
   여        20.6  39.8  193.203883
연령 만10대미만    3.2   8.1  253.125000
   만10-19세  15.9  30.7  193.081761
   만20-29세  34.8  61.5  176.724138
   만30-39세  30.6  46.9  153.267974
   만40-49세  23.6  45.1  191.101695
   만50-59세  14.8  29.8  201.351351
   만60-69세   7.9  18.1  229.113924
   만70세이상    3.5  13.5  385.714286

In [10]:
OTT_개인방송 = pd.DataFrame([OTT["2020"]["개인방송(예능/오락)"], OTT["2021"]["개인방송(예능/오락)"]], index=["2020","2021"]).T

In [12]:
OTT_개인방송["OTT개인방송시청증가율"]=OTT_개인방송["2021"]/OTT_개인방송["2020"]*100
OTT_개인방송

            2020  2021  OTT개인방송시청증가율
전체 소계       73.1  80.5    110.123119
성별 남        75.2  78.6    104.521277
   여        70.8  82.5    116.525424
연령 만10대미만   85.7  71.3     83.197200
   만10-19세  79.6  88.8    111.557789
   만20-29세  73.7  88.7    120.352782
   만30-39세  69.6  86.4    124.137931
   만40-49세  69.2  79.8    115.317919
   만50-59세  73.9  75.2    101.759134
   만60-69세  74.4  69.6     93.548387
   만70세이상   76.0  64.2     84.473684

In [13]:
OTT.rename(columns = {"시청증가율":"OTT전체시청증가율"}, inplace=True)

In [14]:
# OTT시청의 증감률을 확인하고 우리가 알아보고자 하는 OTT에서 영화를 보는 시청 증감률이 차이를 비교하기 위해 dataframe을 합쳐준다
# 추가로 2020년과 2021년의 공통 컬럼인 개인방송부분도 추가해서 비교하겠다.

In [15]:
change = pd.concat([OTT_movie["OTT영화시청증가율"], OTT["OTT전체시청증가율"], OTT_개인방송["OTT개인방송시청증가율"]], axis=1)

In [16]:
# OTT전체시청증감률 대비 OTT영화시청증감률을 비교한다. 

moviechange = change["OTT영화시청증가율"]/change["OTT전체시청증가율"] 
round(np.mean(moviechange),2)
# 전체적으로 OTT시청하는 사람들의 사례수가 증가한 추세인데, OTT에서 영화를 보는 사람들은 OTT전체 시청률대비에도 평균적으로 1.73배 높다. 

personal = change["OTT개인방송시청증가율"]/change["OTT전체시청증가율"] 
round(np.mean(personal),2)
# 한편 공통 컬럼으로 비교하고자 했던 개인방송을 시청하는 사람들은 OTT전체 시청률 대비 0.93배이다.

0.93

In [17]:
# OTT로 영화를 보는 사람들의 수가 많이 늘었음을 확인할 수 있다.

In [18]:
sparemovie= pd.read_csv("data/1년동안가장많이이용한여가공간1순위_영화관비율.csv", encoding="euc-kr", header=[0,1], index_col=[0,1])

In [19]:
sparemovie

통계분류(1)         2016  2018  2019 2020 2021
통계분류(1)          영화관   영화관   영화관  영화관  영화관
전체      소계       4.4   6.8   9.4    3  2.1
성별      남성       4.2   6.1   8.9    3  2.1
        여성       4.6   7.5   9.9    3    2
연령별     15~19세   7.3  10.3  17.3  6.1  4.4
        20대     10.1  12.6  16.5  6.2    4
...              ...   ...   ...  ...  ...
17개 시도별 경남       4.1   7.1   8.4  1.3  0.2
        제주       7.0   9.8   7.9    -  0.3
장애여부별   장애등록     0.0   7.5   8.3  1.5  0.5
        미등록      0.0   5.3     5  2.9    -
        해당사항없음   0.0   6.8   9.4  3.1  2.1

[67 rows x 5 columns]

In [20]:
#위의 OTT 시청자 구분 맞춰주기(전체, 성별, 연령별)

sparetheater = sparemovie.loc[["전체","성별","연령별"],["2020","2021"]]

In [21]:
sparetheater.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10 entries, ('전체', '소계') to ('연령별', '70세이상')
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   (2020, 영화관)  10 non-null     object
 1   (2021, 영화관)  10 non-null     object
dtypes: object(2)
memory usage: 3.4+ KB

In [22]:
sparetheater = sparetheater.astype(float)

In [23]:
sparetheater["여가영화증감률"]=sparetheater["2021"]/sparetheater["2020"]
sparetheater

통계분류(1)    2020 2021   여가영화증감률
통계분류(1)     영화관  영화관
전체  소계      3.0  2.1  0.700000
성별  남성      3.0  2.1  0.700000
    여성      3.0  2.0  0.666667
연령별 15~19세  6.1  4.4  0.721311
    20대     6.2  4.0  0.645161
    30대     4.3  4.2  0.976744
    40대     3.1  1.4  0.451613
    50대     1.8  1.2  0.666667
    60대     0.8  0.4  0.500000
    70세이상   0.3  0.4  1.333333

In [24]:
#1년동안 가장 많이 이용한 여가공간으로 영화관을 뽑은 사람들은 70세이상을 제외하고 모두 줄어들었다.

In [34]:
movietheater = pd.read_excel("data/영화관객수및매출액(2018-2022).xlsx", header=[0,1], index_col=[0])

In [26]:
#movietheater = movietheater.droplevel(axis=1, level=0).T

In [40]:
theater = pd.DataFrame(movietheater["전체"]["관객수"])

In [51]:
theater.loc[2021]/theater.loc[2020]
# 2020년 대비 약간 늘긴했지만 거의 비슷하다고 볼 수 있다. 
# 영화관관람객수는 사실 2019년 대비해서 많이 줄고 2020년과 2021년은 비슷하다.

관객수    1.01692
dtype: float64

In [52]:
theater

             관객수
2018   216385269
2019   226678777
2020    59523967
2021    60531087
2022    92501405
합계    3032329696